# Generated by Django 4.2.7 on 2023-11-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='macllocmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('contain', models.CharField(max_length=25)),
                ('btn', models.CharField(max_length=15)),
            ],
        ),
    ]
