# Generated by Django 4.2.7 on 2023-12-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macllocmedia',
            name='contain',
            field=models.CharField(max_length=500),
        ),
    ]
