# Generated by Django 4.2.7 on 2023-12-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_macllocmedia_image1_macllocmedia_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='macllocmedia',
            name='image2',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
