# Generated by Django 4.2.7 on 2023-12-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_macllocmedia_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='macllocmedia',
            name='contain1',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='macllocmedia',
            name='contain',
            field=models.CharField(max_length=50),
        ),
    ]
