# Generated by Django 4.2.7 on 2023-12-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_macllocmedia_contain1_alter_macllocmedia_contain'),
    ]

    operations = [
        migrations.AddField(
            model_name='macllocmedia',
            name='banner',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
