# Generated by Django 4.2.7 on 2023-12-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_macllocmedia_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='macllocmedia',
            name='banner',
        ),
    ]
