# Generated by Django 4.2.7 on 2023-12-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_macllocmedia_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='macllocmedia',
            name='imagecontain',
            field=models.CharField(default=12, max_length=500),
            preserve_default=False,
        ),
    ]
