# Generated by Django 4.2.7 on 2023-12-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_macllocmedia_imagecontain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macllocmedia',
            name='imagecontain',
            field=models.CharField(max_length=1000),
        ),
    ]
