# Generated by Django 4.2.7 on 2023-12-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_alter_macllocmedia_imagecontain'),
    ]

    operations = [
        migrations.AddField(
            model_name='macllocmedia',
            name='paragraph',
            field=models.CharField(default=3, max_length=2000),
            preserve_default=False,
        ),
    ]
