# Generated by Django 4.2.7 on 2023-12-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0014_macllocmedia_paragraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=1000)),
            ],
        ),
    ]
