# Generated by Django 4.2.7 on 2024-01-19 13:51

import demo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_alter_student_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(default='1234567890', max_length=10, validators=[demo.models.validate_ten_digit]),
        ),
    ]
